window.SIMULATOR_DATA = (() => {
  const hardwareParts = [
    {
      id: "power",
      name: "Fonte ATX",
      short: "PWR",
      icon: "./assets/icons/power.svg",
      description: "Fonte de alimentação ATX e seus conectores.",
    },
    {
      id: "motherboard",
      name: "Placa-mãe",
      short: "MB",
      icon: "./assets/icons/motherboard.svg",
      description: "Placa principal, chipset, soquete e slots.",
    },
    {
      id: "cooler",
      name: "Cooler da CPU",
      short: "FAN",
      icon: "./assets/icons/fan.svg",
      description: "Dissipador e ventilador do processador.",
    },
    {
      id: "memory",
      name: "Memória RAM",
      short: "RAM",
      icon: "./assets/icons/memory.svg",
      description: "Módulo DDR4 de memória principal.",
    },
    {
      id: "storage",
      name: "HD / SSD",
      short: "DISK",
      icon: "./assets/icons/device-ssd.svg",
      alternateIcon: "./assets/icons/device-hdd.svg",
      description: "Unidade de armazenamento SATA: HD ou SSD.",
    },
    {
      id: "gpu",
      name: "Placa de vídeo",
      short: "GPU",
      icon: "./assets/icons/gpu-card.svg",
      description: "Adaptador gráfico instalado no slot PCI Express.",
    },
    {
      id: "network",
      name: "Placa de rede",
      short: "NIC",
      icon: "./assets/icons/ethernet.svg",
      description: "Interface Ethernet PCI Express.",
    },
  ];

  const maintenanceTools = [
    {
      id: "clean-eraser",
      name: "Borracha branca",
      short: "ERASER",
      description: "Limpar suavemente os contatos metálicos e remover todo o resíduo.",
      compatibleParts: ["memory", "gpu", "network"],
    },
    {
      id: "clean-isopropyl",
      name: "Álcool isopropílico",
      short: "IPA",
      description: "Limpar contatos e slot com álcool isopropílico e pincel antiestático.",
      compatibleParts: ["memory", "gpu", "network"],
    },
    {
      id: "reseat",
      name: "Remover e reencaixar",
      short: "RESEAT",
      description: "Refazer o encaixe e conferir travas, cabos e alimentação do componente.",
      compatibleParts: ["memory", "storage", "gpu", "network"],
    },
  ];

  const diagnosticTools = [
    { id: "visual", short: "VIS", name: "Inspeção visual", requiresPower: false },
    { id: "post", short: "POST", name: "Executar POST", requiresPower: true },
    { id: "smart", short: "SMART", name: "Testar HD/SSD", requiresPower: true },
    { id: "thermal", short: "TEMP", name: "Monitorar temperatura", requiresPower: true },
    { id: "network", short: "NET", name: "Testar rede", requiresPower: true },
  ];

  const softwareActions = [
    {
      id: "install-os",
      name: "Instalar o sistema operacional",
      short: "OS",
      icon: "./assets/icons/windows.svg",
      description: "Iniciar a instalação no HD/SSD selecionado.",
    },
    {
      id: "repair-boot",
      name: "Reparar a inicialização",
      short: "BOOT",
      icon: "./assets/icons/windows.svg",
      description: "Reconstruir arquivos e registros de boot.",
    },
    {
      id: "install-driver",
      name: "Instalar driver de rede",
      short: "DRV",
      icon: "./assets/icons/ethernet.svg",
      description: "Instalar o driver correto do controlador Ethernet.",
    },
    {
      id: "remove-malware",
      name: "Verificar e remover malware",
      short: "SEC",
      icon: "./assets/icons/shield.svg",
      description: "Executar verificação completa e colocar ameaças em quarentena.",
    },
    {
      id: "configure-dns",
      name: "Corrigir a configuração DNS",
      short: "DNS",
      icon: "./assets/icons/ethernet.svg",
      description: "Restaurar DNS automático e limpar o cache de resolução.",
    },
    {
      id: "configure-boot",
      name: "Corrigir a ordem de boot",
      short: "UEFI",
      icon: "./assets/icons/motherboard.svg",
      description: "Colocar o gerenciador do sistema antes de USB e rede.",
    },
  ];

  const simulations = {
    "install-os": [
      {
        mode: "setup",
        title: "Instalação do sistema",
        detail: "Inicializando o ambiente de instalação...",
        progress: 4,
        lines: ["Carregando arquivos...", "Detectando dispositivos de armazenamento"],
        delay: 950,
      },
      {
        mode: "setup",
        title: "Instalando o sistema",
        detail: "Copiando arquivos do sistema operacional",
        progress: 28,
        lines: ["Destino: SSD SATA 480 GB", "Copiando arquivos: 28%"],
        delay: 1050,
      },
      {
        mode: "setup",
        title: "Instalando o sistema",
        detail: "Preparando arquivos para instalação",
        progress: 54,
        lines: ["Expandindo imagem do sistema", "Verificando integridade dos arquivos"],
        delay: 1050,
      },
      {
        mode: "setup",
        title: "Instalando recursos",
        detail: "Configurando dispositivos e componentes",
        progress: 78,
        lines: ["Instalando drivers básicos", "Configurando serviços"],
        delay: 1050,
      },
      {
        mode: "setup",
        title: "Finalizando",
        detail: "Configurando o gerenciador de inicialização",
        progress: 96,
        lines: ["Criando Windows Boot Manager", "Aplicando configurações finais"],
        delay: 1050,
      },
      {
        mode: "success",
        title: "Instalação concluída",
        detail: "O computador será reiniciado.",
        progress: 100,
        lines: ["Sistema operacional instalado com sucesso."],
        delay: 900,
      },
    ],
    "repair-boot": [
      {
        mode: "terminal",
        title: "Ambiente de Recuperação",
        detail: "Prompt de comando administrativo",
        progress: 12,
        lines: ["X:\\Sources> bootrec /scanos", "Instalações identificadas: 1"],
        delay: 950,
      },
      {
        mode: "terminal",
        title: "Reconstruindo BCD",
        detail: "Adicionando instalação ao menu de inicialização",
        progress: 48,
        lines: ["X:\\Sources> bootrec /rebuildbcd", "Operação concluída com êxito."],
        delay: 1100,
      },
      {
        mode: "terminal",
        title: "Verificando arquivos",
        detail: "SFC verificando arquivos protegidos",
        progress: 82,
        lines: ["sfc /scannow /offbootdir=C:\\", "Proteção de Recursos corrigiu arquivos corrompidos."],
        delay: 1150,
      },
      {
        mode: "success",
        title: "Reparo concluído",
        detail: "Inicialização restaurada.",
        progress: 100,
        lines: ["Windows Boot Manager localizado", "Reiniciando o computador..."],
        delay: 900,
      },
    ],
    "install-driver": [
      {
        mode: "device",
        title: "Gerenciador de Dispositivos",
        detail: "Controlador Ethernet — código 28",
        progress: 10,
        lines: ["O driver deste dispositivo não está instalado."],
        delay: 850,
      },
      {
        mode: "device",
        title: "Atualizar driver",
        detail: "Procurando software de driver compatível...",
        progress: 42,
        lines: ["Hardware ID: PCI\\VEN_10EC&DEV_8168", "Pacote assinado localizado"],
        delay: 1050,
      },
      {
        mode: "device",
        title: "Instalando dispositivo",
        detail: "Realtek PCIe GbE Family Controller",
        progress: 78,
        lines: ["Copiando arquivos do driver", "Iniciando serviço rt640x64"],
        delay: 1050,
      },
      {
        mode: "success",
        title: "Dispositivo pronto",
        detail: "Ethernet conectada a 1,0 Gbit/s",
        progress: 100,
        lines: ["Endereço obtido via DHCP: 192.168.10.48"],
        delay: 900,
      },
    ],
    "remove-malware": [
      {
        mode: "security",
        title: "Segurança do Sistema",
        detail: "Iniciando verificação completa",
        progress: 8,
        lines: ["Arquivos verificados: 1.240", "Ameaças encontradas: 0"],
        delay: 850,
      },
      {
        mode: "security",
        title: "Verificação em andamento",
        detail: "Analisando processos e itens de inicialização",
        progress: 47,
        lines: ["Arquivos verificados: 48.912", "Ameaça detectada: Trojan:Win32/FakeUpdate"],
        delay: 1100,
      },
      {
        mode: "security",
        title: "Aplicando ações",
        detail: "Interrompendo processo e removendo persistência",
        progress: 82,
        lines: ["update_service.exe encerrado", "Item movido para quarentena"],
        delay: 1100,
      },
      {
        mode: "success",
        title: "Verificação concluída",
        detail: "A ameaça foi removida.",
        progress: 100,
        lines: ["Uso de CPU normalizado: 4%", "Proteção em tempo real ativada"],
        delay: 900,
      },
    ],
    "configure-dns": [
      {
        mode: "terminal",
        title: "Configuração de Rede",
        detail: "Restaurando DNS automático",
        progress: 22,
        lines: ["C:\\> netsh interface ip set dns name=\"Ethernet\" dhcp", "Ok."],
        delay: 900,
      },
      {
        mode: "terminal",
        title: "Limpando cache DNS",
        detail: "Descartando registros locais antigos",
        progress: 55,
        lines: ["C:\\> ipconfig /flushdns", "Cache do DNS Resolver limpo com êxito."],
        delay: 1050,
      },
      {
        mode: "terminal",
        title: "Testando resolução",
        detail: "Consultando o servidor DNS",
        progress: 84,
        lines: ["C:\\> nslookup escola.rs.gov.br", "Servidor: 192.168.10.1", "Resposta não autoritativa recebida"],
        delay: 1100,
      },
      {
        mode: "success",
        title: "Internet disponível",
        detail: "Resolução de nomes restaurada.",
        progress: 100,
        lines: ["Ping por nome: sucesso", "Perda de pacotes: 0%"],
        delay: 900,
      },
    ],
    "configure-boot": [
      {
        mode: "bios",
        title: "SIMULAB UEFI — BOOT",
        detail: "Prioridade atual de inicialização",
        progress: 20,
        lines: ["1. USB Mass Storage", "2. Windows Boot Manager", "3. Network PXE"],
        delay: 950,
      },
      {
        mode: "bios",
        title: "Alterando prioridade",
        detail: "Movendo Windows Boot Manager para a primeira posição",
        progress: 58,
        lines: ["1. Windows Boot Manager", "2. USB Mass Storage", "3. Network PXE"],
        delay: 1100,
      },
      {
        mode: "bios",
        title: "Save & Exit",
        detail: "Salvando configuração UEFI",
        progress: 88,
        lines: ["Save configuration and reset? [Yes]", "Reiniciando..."],
        delay: 1000,
      },
      {
        mode: "success",
        title: "Sistema iniciado",
        detail: "Windows Boot Manager executado corretamente.",
        progress: 100,
        lines: ["Ordem de boot corrigida."],
        delay: 900,
      },
    ],
  };

  const cases = [
    {
      id: "storage-failure",
      kind: "hardware",
      level: 2,
      title: "Falha de leitura no HD/SSD",
      symptom: "A inicialização trava, aparecem erros de E/S e a UEFI exibe o alerta S.M.A.R.T. Status BAD.",
      boot: "disk-failure",
      correctPart: "storage",
      explanation: "O HD/SSD apresentava setores instáveis e falhas de leitura. A substituição da unidade eliminou os erros e permitiu uma instalação íntegra.",
      diagnostics: {
        visual: "Cabos SATA e alimentação estão firmes. Não há conector solto.",
        post: "POST concluído com alerta: S.M.A.R.T. Status BAD — Backup and Replace.",
        smart: "Reallocated Sector Count: 184; Current Pending Sector: 37; estado crítico.",
        thermal: "CPU 39 °C; placa-mãe 34 °C; temperaturas normais.",
        network: "Interface de rede normal; sistema não conclui o boot devido a erros de disco.",
      },
    },
    {
      id: "memory-failure",
      kind: "hardware",
      level: 2,
      title: "Bipes de memória e ausência de vídeo",
      symptom: "O PC liga, repete três bipes longos e não conclui o POST nem apresenta imagem.",
      boot: "memory-error",
      correctPart: "memory",
      explanation: "O módulo DDR4 apresentava falha elétrica. A troca da memória RAM permitiu concluir o treinamento de memória e o POST.",
      diagnostics: {
        visual: "Módulos encaixados e travas fechadas; não há sujeira aparente nos contatos.",
        post: "Código DRAM; sequência de três bipes longos. Teste de memória interrompido.",
        smart: "HD/SSD não testado porque o POST foi interrompido antes da enumeração SATA.",
        thermal: "Sem leitura térmica completa; desligamento ocorre ainda no POST.",
        network: "Interface não inicializada porque o POST não foi concluído.",
      },
    },
    {
      id: "memory-contact-oxidation",
      kind: "hardware",
      level: 2,
      title: "Mau contato nos módulos de memória",
      symptom: "Após ficar meses sem uso, o PC alterna entre três bipes, LED DRAM aceso e inicialização normal quando os módulos são movimentados.",
      boot: "memory-contact",
      correctPart: "memory",
      correctMaintenance: "clean-eraser",
      explanation: "Os módulos estavam funcionais, mas havia oxidação superficial nos contatos. A limpeza suave com borracha branca, a remoção completa dos resíduos e o reencaixe restauraram o treinamento da memória sem substituir a peça.",
      diagnostics: {
        visual: "Há escurecimento e película irregular nos contatos dourados dos módulos; travas e slots estão íntegros.",
        post: "Falha DRAM intermitente; o POST conclui quando o módulo é pressionado ou movimentado.",
        smart: "HD/SSD saudável; o teste só fica disponível quando o POST conclui.",
        thermal: "Temperaturas normais quando a estação consegue inicializar.",
        network: "Interface normal; o defeito ocorre antes da inicialização da rede.",
      },
    },
    {
      id: "power-failure",
      kind: "hardware",
      level: 1,
      title: "Computador não apresenta nenhum sinal",
      symptom: "Tomada e cabo estão normais, mas não existem LEDs, ventoinhas, bipes ou tensão de standby.",
      boot: "no-power",
      correctPart: "power",
      explanation: "A fonte ATX não gerava a linha +5VSB. A substituição restabeleceu o sinal de standby e a partida da placa-mãe.",
      diagnostics: {
        visual: "Cabo de energia e conectores ATX estão corretamente encaixados.",
        post: "POST não iniciado. Placa-mãe sem alimentação de standby.",
        smart: "Indisponível: o equipamento não energiza.",
        thermal: "Indisponível: sensores sem alimentação.",
        network: "LEDs da interface apagados mesmo com cabo conectado.",
      },
    },
    {
      id: "cooler-failure",
      kind: "hardware",
      level: 2,
      title: "CPU aquece e o computador desliga",
      symptom: "Após iniciar, a temperatura ultrapassa 95 °C e o sistema executa desligamento de proteção.",
      boot: "overheat",
      correctPart: "cooler",
      explanation: "O ventilador do cooler estava travado e registrava 0 RPM. A troca do conjunto estabilizou a CPU em temperatura segura.",
      diagnostics: {
        visual: "Ventoinha do processador tenta partir, mas permanece travada.",
        post: "CPU FAN ERROR detectado durante o POST.",
        smart: "HD/SSD saudável; S.M.A.R.T. sem alertas.",
        thermal: "CPU: 98 °C; CPU_FAN: 0 RPM; thermal throttling ativo.",
        network: "Rede normal até o desligamento térmico.",
      },
    },
    {
      id: "gpu-failure",
      kind: "hardware",
      level: 3,
      title: "Imagem com artefatos e travamentos",
      symptom: "A tela apresenta blocos coloridos, linhas e reinicializações do driver de vídeo mesmo com cabo e monitor normais.",
      boot: "video-artifacts",
      correctPart: "gpu",
      explanation: "A placa de vídeo apresentava falha na memória gráfica. A substituição removeu os artefatos e estabilizou a saída de vídeo.",
      diagnostics: {
        visual: "Cabo HDMI e alimentação PCIe firmes; monitor funciona em outra estação.",
        post: "POST concluído; adaptador gráfico reconhecido, mas com falhas sob carga.",
        smart: "HD/SSD saudável; leitura e escrita normais.",
        thermal: "GPU: 61 °C; CPU: 42 °C. Sem superaquecimento no momento do erro.",
        network: "Rede normal. O defeito permanece mesmo sem conexão de rede.",
      },
    },
    {
      id: "gpu-contact-contamination",
      kind: "hardware",
      level: 2,
      title: "Contato PCIe contaminado na placa de vídeo",
      symptom: "A saída de vídeo alterna entre imagem normal, artefatos e ausência de sinal; pressionar levemente a placa altera o comportamento.",
      boot: "gpu-contact",
      correctPart: "gpu",
      correctMaintenance: "clean-isopropyl",
      explanation: "A GPU estava funcional, mas resíduos nos contatos PCIe e no slot causavam perda intermitente de sinal. A limpeza com álcool isopropílico, pincel antiestático e secagem completa restaurou a conexão sem trocar a placa.",
      diagnostics: {
        visual: "Conector PCIe apresenta resíduo e marcas superficiais; trava, cabo de vídeo e alimentação auxiliar estão firmes.",
        post: "O adaptador gráfico aparece e desaparece da enumeração PCIe entre as tentativas.",
        smart: "HD/SSD saudável; leitura normal.",
        thermal: "GPU 44 °C e CPU 39 °C; não há superaquecimento.",
        network: "Rede normal; o defeito muda quando a placa de vídeo é movimentada.",
      },
    },
    {
      id: "storage-loose-connection",
      kind: "hardware",
      level: 1,
      title: "HD/SSD desaparece após movimentar o gabinete",
      symptom: "A UEFI ora detecta o SSD, ora mostra SATA Port Not Present; a falha começou depois que o computador foi transportado.",
      boot: "storage-intermittent",
      correctPart: "storage",
      correctMaintenance: "reseat",
      explanation: "O HD/SSD estava saudável. O conector SATA havia perdido pressão mecânica durante o transporte; remover, conferir e reencaixar os cabos de dados e alimentação restabeleceu a detecção estável sem substituir a unidade.",
      diagnostics: {
        visual: "O cabo SATA está parcialmente encaixado e não atingiu o fim do conector da unidade.",
        post: "SATA Port 1 alterna entre SIMULAB SSD 480 GB e Not Present.",
        smart: "Quando detectado, o SSD informa S.M.A.R.T. saudável e zero setores realocados.",
        thermal: "CPU, placa-mãe e SSD apresentam temperaturas normais.",
        network: "Interface normal; a inicialização falha quando o SSD não é enumerado.",
      },
    },
    {
      id: "network-hardware-failure",
      kind: "hardware",
      level: 2,
      title: "Placa Ethernet não estabelece link",
      symptom: "Cabo e switch foram testados, mas os LEDs da interface permanecem apagados e o adaptador desaparece intermitentemente.",
      boot: "network-card-failure",
      correctPart: "network",
      explanation: "A interface Ethernet apresentava falha física no transceptor. A substituição da placa de rede restabeleceu o enlace Gigabit.",
      diagnostics: {
        visual: "Cabo RJ-45 e porta do switch funcionam em outro equipamento.",
        post: "Controlador Ethernet falha intermitentemente na enumeração PCIe.",
        smart: "HD/SSD saudável; sistema operacional inicia normalmente.",
        thermal: "Temperaturas internas normais.",
        network: "Sem link físico; LEDs apagados; contador de interface indisponível.",
      },
    },
    {
      id: "new-drive-no-os",
      kind: "software",
      level: 1,
      title: "HD/SSD novo sem sistema operacional",
      symptom: "O HD/SSD é reconhecido pela UEFI, mas aparece “No bootable device” porque ainda não existe sistema instalado.",
      boot: "no-os",
      correctAction: "install-os",
      explanation: "O hardware estava funcionando. A instalação criou as partições, copiou o sistema e configurou o gerenciador de inicialização.",
      diagnostics: {
        visual: "HD/SSD novo corretamente instalado e conectado.",
        post: "POST concluído; SSD SATA de 480 GB reconhecido.",
        smart: "Unidade nova; S.M.A.R.T. saudável e sem setores realocados.",
        thermal: "Temperaturas normais.",
        network: "Indisponível enquanto não houver sistema operacional.",
      },
    },
    {
      id: "boot-corruption",
      kind: "software",
      level: 3,
      title: "Sistema preso no reparo automático",
      symptom: "A UEFI reconhece o HD/SSD, mas a inicialização retorna ao ambiente de recuperação com o código 0xc0000098.",
      boot: "repair-loop",
      correctAction: "repair-boot",
      explanation: "O BCD e arquivos de boot estavam corrompidos. A reconstrução do gerenciador e a verificação SFC restauraram a inicialização.",
      diagnostics: {
        visual: "Nenhuma anomalia física nos componentes.",
        post: "POST concluído e Windows Boot Manager selecionado.",
        smart: "HD/SSD saudável; volume acessível pelo ambiente de recuperação.",
        thermal: "Temperaturas normais.",
        network: "Sistema não alcança a etapa de carregamento da rede.",
      },
    },
    {
      id: "network-driver",
      kind: "software",
      level: 2,
      title: "Controlador Ethernet sem driver",
      symptom: "O cabo possui link físico, mas o sistema mostra “Controlador Ethernet” com código 28 e não cria interface de rede.",
      boot: "driver-missing",
      correctAction: "install-driver",
      explanation: "O dispositivo físico estava normal, porém faltava o driver. A instalação do pacote compatível criou a interface e obteve IP via DHCP.",
      diagnostics: {
        visual: "LED de link aceso no computador e no switch.",
        post: "Controlador Ethernet detectado no barramento PCIe.",
        smart: "HD/SSD saudável.",
        thermal: "Temperaturas normais.",
        network: "Gerenciador de Dispositivos: código 28 — driver não instalado.",
      },
    },
    {
      id: "malware",
      kind: "software",
      level: 3,
      title: "Sistema lento e com janelas indesejadas",
      symptom: "Após o login, um processo desconhecido mantém a CPU em 96% e cria conexões externas repetidas.",
      boot: "malware",
      correctAction: "remove-malware",
      explanation: "Um trojan persistente estava ativo na inicialização. A verificação completa encerrou o processo, removeu a persistência e colocou a ameaça em quarentena.",
      diagnostics: {
        visual: "Hardware sem anomalias aparentes.",
        post: "POST concluído sem erros.",
        smart: "HD/SSD saudável e com desempenho normal.",
        thermal: "CPU 68 °C devido à carga elevada, sem atingir limite térmico.",
        network: "update_service.exe mantém conexões externas não solicitadas.",
      },
    },
    {
      id: "dns-error",
      kind: "software",
      level: 2,
      title: "Internet funciona por IP, mas não por nome",
      symptom: "O ping para 1.1.1.1 responde, porém sites não abrem e o nslookup consulta um servidor inexistente.",
      boot: "dns-error",
      correctAction: "configure-dns",
      explanation: "A pilha TCP/IP estava normal, mas o DNS manual apontava para 192.168.10.254 sem resposta. O retorno ao DNS automático restaurou a resolução.",
      diagnostics: {
        visual: "Cabo e LEDs de link normais.",
        post: "POST concluído sem erros.",
        smart: "HD/SSD saudável.",
        thermal: "Temperaturas normais.",
        network: "Ping 1.1.1.1: sucesso; nslookup: timeout em 192.168.10.254.",
      },
    },
    {
      id: "boot-order",
      kind: "software",
      level: 2,
      title: "PC tenta iniciar por um pendrive sem sistema",
      symptom: "Com um pendrive de dados conectado, aparece “Missing operating system”; o HD/SSD está saudável e contém o sistema.",
      boot: "usb-boot",
      correctAction: "configure-boot",
      explanation: "A UEFI priorizava dispositivos USB antes do Windows Boot Manager. A correção da ordem de boot fez o sistema iniciar pelo HD/SSD correto.",
      diagnostics: {
        visual: "Pendrive de dados conectado à porta frontal.",
        post: "POST concluído; primeira tentativa de boot direcionada a USB Mass Storage.",
        smart: "HD/SSD reconhecido, saudável e com sistema instalado.",
        thermal: "Temperaturas normais.",
        network: "Não aplicável antes da inicialização do sistema.",
      },
    },
  ];

  return {
    hardwareParts,
    maintenanceTools,
    diagnosticTools,
    softwareActions,
    simulations,
    cases,
  };
})();
