window.SIMULATOR_DATA = (() => {
  const components = [
    {
      id: "power",
      category: "hardware",
      short: "PWR",
      name: "Fonte e energia",
      description: "Converte a tensão da rede e distribui as linhas DC para a placa-mãe e os periféricos.",
      metrics: [
        ["Entrada", "220 V AC"],
        ["Linhas", "+12 V / +5 V / +3,3 V"],
        ["Sinal", "PS_ON#"],
        ["Estado base", "Standby"],
      ],
    },
    {
      id: "motherboard",
      category: "hardware",
      short: "MB",
      name: "Placa-mãe",
      description: "Interliga CPU, memória, armazenamento, firmware e interfaces de entrada e saída.",
      metrics: [
        ["Firmware", "UEFI 2.8"],
        ["Chipset", "B660"],
        ["POST", "Disponível"],
        ["CMOS", "3,02 V"],
      ],
    },
    {
      id: "cpu",
      category: "hardware",
      short: "CPU",
      name: "Processador e cooler",
      description: "Executa instruções e depende do conjunto dissipador, pasta térmica e ventilador.",
      metrics: [
        ["Núcleos", "6"],
        ["Clock base", "2,50 GHz"],
        ["TjMax", "100 °C"],
        ["Cooler", "PWM"],
      ],
    },
    {
      id: "memory",
      category: "hardware",
      short: "RAM",
      name: "Memória RAM",
      description: "Armazena temporariamente dados e instruções em uso pelo processador.",
      metrics: [
        ["Capacidade", "16 GB"],
        ["Tipo", "DDR4"],
        ["Frequência", "3200 MT/s"],
        ["Módulos", "2 × 8 GB"],
      ],
    },
    {
      id: "storage",
      category: "hardware",
      short: "SSD",
      name: "Armazenamento",
      description: "Mantém o sistema operacional, aplicações e arquivos em memória não volátil.",
      metrics: [
        ["Unidade", "SSD SATA"],
        ["Capacidade", "480 GB"],
        ["Interface", "SATA III"],
        ["S.M.A.R.T.", "Ativo"],
      ],
    },
    {
      id: "video",
      category: "hardware",
      short: "GPU",
      name: "Vídeo e monitor",
      description: "Produz o sinal gráfico e o transporta até o monitor por meio do cabo de vídeo.",
      metrics: [
        ["Saída", "HDMI"],
        ["Resolução", "1920 × 1080"],
        ["Sinal", "Digital"],
        ["Monitor", "LED 24\""],
      ],
    },
    {
      id: "network-card",
      category: "hardware",
      short: "NIC",
      name: "Placa de rede",
      description: "Interface Ethernet responsável pelo enlace físico e pela transmissão de quadros.",
      metrics: [
        ["Padrão", "Gigabit Ethernet"],
        ["Conector", "RJ-45"],
        ["MAC", "00:1A:4B:7C:92:10"],
        ["LEDs", "Link / atividade"],
      ],
    },
    {
      id: "peripherals",
      category: "hardware",
      short: "I/O",
      name: "Cabos e periféricos",
      description: "Conjunto de conexões externas: energia, vídeo, USB, rede, teclado e mouse.",
      metrics: [
        ["Vídeo", "HDMI"],
        ["Entrada", "USB"],
        ["Rede", "RJ-45"],
        ["Energia", "IEC C13"],
      ],
    },
    {
      id: "firmware",
      category: "software",
      short: "UEFI",
      name: "BIOS / UEFI",
      description: "Inicializa o hardware, executa o POST e transfere o controle ao carregador do sistema.",
      metrics: [
        ["Modo", "UEFI"],
        ["Secure Boot", "Ativo"],
        ["Data", "2025-11-18"],
        ["Boot", "Automático"],
      ],
    },
    {
      id: "operating-system",
      category: "software",
      short: "OS",
      name: "Sistema operacional",
      description: "Gerencia processos, arquivos, memória, dispositivos e a interface de usuário.",
      metrics: [
        ["Arquitetura", "64 bits"],
        ["Inicialização", "UEFI"],
        ["Sistema de arquivos", "NTFS"],
        ["Recuperação", "Ativa"],
      ],
    },
    {
      id: "drivers",
      category: "software",
      short: "DRV",
      name: "Drivers",
      description: "Camada de software que permite ao sistema operacional controlar cada dispositivo.",
      metrics: [
        ["Assinatura", "Verificável"],
        ["PnP", "Ativo"],
        ["Catálogo", "Local"],
        ["Atualização", "Manual"],
      ],
    },
    {
      id: "network-stack",
      category: "software",
      short: "NET",
      name: "Rede TCP/IP",
      description: "Configura endereçamento, rota padrão, resolução de nomes e comunicação em rede.",
      metrics: [
        ["IPv4", "DHCP"],
        ["IPv6", "Ativo"],
        ["DNS", "Automático"],
        ["Firewall", "Ativo"],
      ],
    },
    {
      id: "security",
      category: "software",
      short: "SEC",
      name: "Processos e segurança",
      description: "Permite analisar consumo de recursos, inicialização, serviços e ameaças ativas.",
      metrics: [
        ["Proteção", "Tempo real"],
        ["Inicialização", "Monitorada"],
        ["Quarentena", "Disponível"],
        ["Logs", "Ativos"],
      ],
    },
  ];

  const tools = [
    { id: "visual", short: "VIS", name: "Inspeção visual", requiresPower: false },
    { id: "post", short: "POST", name: "Teste de inicialização", requiresPower: true },
    { id: "voltage", short: "VDC", name: "Medição elétrica", requiresPower: false },
    { id: "system", short: "SYS", name: "Monitor do sistema", requiresPower: true },
    { id: "network", short: "PING", name: "Diagnóstico de rede", requiresPower: true },
  ];

  const cases = [
    {
      id: "power-cable",
      level: 1,
      title: "Computador não apresenta nenhum sinal",
      symptom: "Ao pressionar o botão, não há LEDs, ventoinhas, bipes ou imagem no monitor.",
      diagnosis: "Cabo de energia da fonte desconectado",
      component: "power",
      boot: "no-power",
      explanation: "O cabo IEC da fonte estava parcialmente desconectado. Sem alimentação AC, a linha de standby não é gerada e o comando de partida não produz resposta.",
      diagnostics: {
        visual: "O conector IEC C13 está fora do encaixe completo na fonte; não há dano aparente no cabo.",
        post: "Nenhuma resposta ao comando de partida. O POST não é iniciado.",
        voltage: "Entrada da fonte: 0 V AC. Tomada da bancada: 220 V AC.",
        system: "Indisponível: o equipamento não energiza.",
        network: "Indisponível: a interface de rede está sem alimentação.",
      },
      clues: {
        power: "A fonte não recebe tensão na entrada. O conector está fisicamente fora do encaixe completo.",
        peripherals: "A tomada está energizada, mas o cabo IEC está solto junto ao gabinete.",
      },
    },
    {
      id: "ram-seating",
      level: 2,
      title: "Liga, emite bipes e não exibe vídeo",
      symptom: "As ventoinhas giram, porém o monitor permanece sem sinal e a placa-mãe repete uma sequência de bipes.",
      diagnosis: "Memória RAM mal encaixada",
      component: "memory",
      boot: "beep-no-video",
      explanation: "Um dos módulos DDR4 não estava travado no slot. A falha na etapa de treinamento da memória interrompeu o POST antes da inicialização do vídeo.",
      diagnostics: {
        visual: "O fecho direito do segundo slot DIMM está aberto e o módulo apresenta leve desalinhamento.",
        post: "POST interrompido no código DRAM. Sequência sonora: 3 bipes longos, repetindo.",
        voltage: "Linhas +12 V, +5 V e +3,3 V dentro da tolerância.",
        system: "Indisponível: o sistema operacional não chegou a iniciar.",
        network: "Indisponível: a inicialização foi interrompida antes da carga do sistema.",
      },
      clues: {
        memory: "DIMM_B1 não está nivelado; a trava lateral não fechou. O módulo não é detectado pelo POST.",
        motherboard: "LED de diagnóstico DRAM permanece aceso. CPU e VGA não registram erro.",
      },
    },
    {
      id: "ssd-disconnected",
      level: 2,
      title: "UEFI informa ausência de dispositivo de boot",
      symptom: "O equipamento passa pelo POST, mas interrompe a inicialização com a mensagem “No bootable device”.",
      diagnosis: "Cabo SATA do SSD desconectado",
      component: "storage",
      boot: "no-boot-device",
      explanation: "O cabo de dados SATA estava desconectado do SSD. A UEFI completou o POST, mas não encontrou a unidade que contém o carregador do sistema.",
      diagnostics: {
        visual: "O SSD está alimentado, porém o cabo de dados SATA está solto na extremidade da unidade.",
        post: "POST concluído. Nenhum dispositivo SATA foi enumerado na porta SATA_1.",
        voltage: "Alimentação do SSD: +5,04 V. Fonte operando dentro da tolerância.",
        system: "Indisponível: nenhum volume de sistema foi montado.",
        network: "Indisponível: o sistema operacional não foi carregado.",
      },
      clues: {
        storage: "A unidade não aparece na tabela da UEFI. Alimentação presente, enlace SATA ausente.",
        peripherals: "O cabo SATA de dados está livre junto ao SSD; o cabo de alimentação permanece conectado.",
        firmware: "A lista de dispositivos de armazenamento está vazia. A ordem de boot está correta.",
      },
    },
    {
      id: "cpu-overheat",
      level: 3,
      title: "Desliga poucos minutos após iniciar",
      symptom: "O sistema carrega normalmente, torna-se lento e desliga sozinho após forte aumento da temperatura.",
      diagnosis: "Cooler do processador parado",
      component: "cpu",
      boot: "overheat",
      explanation: "O conector CPU_FAN estava desconectado. Sem rotação do ventilador, a CPU atingiu o limite térmico e a placa-mãe executou o desligamento de proteção.",
      diagnostics: {
        visual: "O ventilador do dissipador não gira. O cabo CPU_FAN está próximo do conector, mas desconectado.",
        post: "POST concluído com aviso: CPU FAN ERROR. Inicialização permitida após timeout.",
        voltage: "Fonte estável. Não há queda relevante nas linhas principais durante a carga.",
        system: "CPU: 98 °C, clock reduzido para 0,78 GHz, thermal throttling ativo.",
        network: "Enlace e conectividade normais antes do desligamento térmico.",
      },
      clues: {
        cpu: "Temperatura sobe rapidamente de 52 °C para 98 °C. Leitura CPU_FAN: 0 RPM.",
        motherboard: "Proteção térmica registra evento crítico; tensões e VRM permanecem normais.",
      },
    },
    {
      id: "video-cable",
      level: 1,
      title: "Computador liga, mas o monitor mostra “Sem sinal”",
      symptom: "O gabinete aparenta iniciar normalmente, sem bipes de erro, enquanto o monitor não recebe imagem.",
      diagnosis: "Cabo HDMI conectado na saída errada",
      component: "video",
      boot: "display-cable",
      explanation: "O cabo HDMI estava ligado à saída da placa-mãe, mas a configuração utiliza GPU dedicada e processador sem vídeo integrado. O sistema iniciou sem enviar sinal à porta escolhida.",
      diagnostics: {
        visual: "O HDMI está conectado à placa-mãe; a GPU dedicada possui uma saída HDMI livre.",
        post: "POST concluído sem erros. O sistema operacional responde ao teclado.",
        voltage: "Alimentação da GPU e da placa-mãe dentro da tolerância.",
        system: "Sistema carregado e operacional; diagnóstico local sem exibição indisponível.",
        network: "Host responde ao ping na rede local, confirmando que o sistema foi inicializado.",
      },
      clues: {
        video: "Monitor detecta conexão física, porém não recebe vídeo. HDMI está na saída da placa-mãe; GPU dedicada está ativa.",
        peripherals: "O cabo de vídeo está íntegro e encaixado, mas conectado à porta HDMI incorreta.",
        cpu: "O modelo instalado não possui vídeo integrado habilitado.",
      },
    },
    {
      id: "network-driver",
      level: 2,
      title: "Sistema inicia sem acesso à rede",
      symptom: "Outros computadores navegam normalmente, mas esta estação mostra a interface Ethernet indisponível.",
      diagnosis: "Driver da placa de rede ausente",
      component: "drivers",
      boot: "network-offline",
      explanation: "O controlador Ethernet foi detectado pelo barramento PCIe, mas não possuía driver compatível. Por isso, nenhuma interface de rede foi criada no sistema.",
      diagnostics: {
        visual: "Cabo RJ-45 encaixado; LED de link aceso no switch e na interface do computador.",
        post: "POST concluído. Controlador Ethernet detectado no barramento PCIe.",
        voltage: "Alimentação e sinal físico da interface dentro do esperado.",
        system: "Gerenciador de Dispositivos: Controlador Ethernet com código 28 — drivers não instalados.",
        network: "Nenhuma interface Ethernet disponível para obter endereço IP.",
      },
      clues: {
        "network-card": "Link físico ativo a 1 Gbit/s. Não há indício de defeito elétrico na interface.",
        drivers: "Controlador Ethernet aparece como dispositivo desconhecido. Código 28.",
        "network-stack": "Não existe adaptador vinculado à pilha TCP/IP; DHCP não chegou a ser executado.",
      },
    },
    {
      id: "malware-load",
      level: 3,
      title: "Computador extremamente lento após o login",
      symptom: "A área de trabalho abre, mas o uso de CPU permanece próximo de 100% e surgem janelas não solicitadas.",
      diagnosis: "Malware consumindo recursos do sistema",
      component: "security",
      boot: "malware",
      explanation: "Um processo malicioso configurado na inicialização consumia CPU, criava conexões externas e exibia publicidade. Hardware, temperaturas e armazenamento estavam normais.",
      diagnostics: {
        visual: "Nenhuma anomalia física. Ventoinhas e conexões operam normalmente.",
        post: "POST concluído sem erros de hardware.",
        voltage: "Todas as linhas da fonte estão estáveis.",
        system: "Processo update_service.exe: 92% de CPU, editor desconhecido, inicialização automática.",
        network: "Conexões repetidas do processo update_service.exe para múltiplos endereços externos.",
      },
      clues: {
        security: "Proteção em tempo real está desativada. Processo não assinado mantém 92% de CPU e persistência na inicialização.",
        "operating-system": "Arquivos essenciais íntegros; consumo anormal está concentrado em um processo de terceiros.",
        storage: "S.M.A.R.T. normal, latência de leitura adequada e 61% de espaço livre.",
      },
    },
    {
      id: "boot-order",
      level: 2,
      title: "Inicialização tenta usar um pendrive sem sistema",
      symptom: "Com um dispositivo USB conectado, a máquina exibe erro de boot; sem ele, o sistema inicia normalmente.",
      diagnosis: "Ordem de boot configurada incorretamente",
      component: "firmware",
      boot: "usb-boot",
      explanation: "A prioridade da UEFI estava configurada para iniciar por USB antes do Windows Boot Manager. O pendrive conectado não possuía um carregador válido.",
      diagnostics: {
        visual: "Pendrive de dados conectado à porta frontal. Cabos internos e SSD aparentam normais.",
        post: "POST concluído. Primeira tentativa de boot direcionada a USB Mass Storage.",
        voltage: "Alimentação normal em todos os dispositivos.",
        system: "O sistema do SSD inicia quando o pendrive é removido.",
        network: "Teste possível somente após remover o USB; conectividade então opera normalmente.",
      },
      clues: {
        firmware: "Prioridade atual: 1) USB Mass Storage; 2) Windows Boot Manager; 3) Rede PXE.",
        storage: "SSD reconhecido, S.M.A.R.T. normal e Windows Boot Manager presente.",
        peripherals: "Pendrive sem partição inicializável está conectado durante a partida.",
      },
    },
    {
      id: "system-corruption",
      level: 3,
      title: "Sistema entra em reparo automático continuamente",
      symptom: "Após o POST, o carregamento falha e retorna para a tela de recuperação em todas as tentativas.",
      diagnosis: "Arquivos de inicialização do sistema corrompidos",
      component: "operating-system",
      boot: "repair-loop",
      explanation: "O BCD e arquivos essenciais de inicialização estavam inconsistentes após uma interrupção durante atualização. O SSD foi reconhecido e não apresentou falha física.",
      diagnostics: {
        visual: "Nenhuma anomalia física nos cabos ou componentes internos.",
        post: "POST concluído. SSD reconhecido e selecionado corretamente para boot.",
        voltage: "Fonte e alimentação do SSD estáveis.",
        system: "Ambiente de recuperação: erro 0xc0000098; dados de configuração de inicialização inválidos.",
        network: "Não executado: o sistema não conclui a inicialização.",
      },
      clues: {
        "operating-system": "WinRE registra erro 0xc0000098 e falha na leitura da configuração BCD.",
        storage: "S.M.A.R.T. sem alertas, leitura consistente e volume de sistema acessível no ambiente de recuperação.",
        firmware: "Windows Boot Manager está em primeiro lugar e aponta para o SSD correto.",
      },
    },
    {
      id: "dns-misconfigured",
      level: 3,
      title: "Acessa por IP, mas não abre sites por nome",
      symptom: "O computador alcança endereços IP externos, porém navegadores informam falha de resolução de nomes.",
      diagnosis: "Servidor DNS configurado incorretamente",
      component: "network-stack",
      boot: "dns-error",
      explanation: "A interface possuía endereço IP e rota válidos, mas apontava para um servidor DNS inexistente. A conectividade IP funcionava; somente a resolução de nomes falhava.",
      diagnostics: {
        visual: "Cabo e LEDs de link normais.",
        post: "POST e inicialização concluídos sem erros.",
        voltage: "Interface de rede alimentada e enlace físico estável.",
        system: "Adaptador ativo com IPv4 192.168.10.48/24 e gateway 192.168.10.1.",
        network: "Ping 1.1.1.1: sucesso. nslookup: tempo esgotado no servidor 192.168.10.254.",
      },
      clues: {
        "network-card": "Enlace ativo, sem perdas ou erros de quadro.",
        "network-stack": "DNS manual: 192.168.10.254, sem resposta. Gateway e DHCP operacionais.",
        drivers: "Driver da interface carregado e sem códigos de erro.",
      },
    },
  ];

  return { components, tools, cases };
})();
